using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;


/*
 * Problem 2
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

namespace Prob2_Even_Fibonacci_numbers
{
    class Program
    {
        static void Main(string[] args)
        {
            int firstFibNumber = 1;
            int secondFibNumber = 2;
            int newNumber = 0;
            int sumOfAllEvenFib = 0;

            while(secondFibNumber <= 4000000)
            {
                if((secondFibNumber % 2) == 0)
                {
                    sumOfAllEvenFib += secondFibNumber;
                }

                newNumber = secondFibNumber;
                secondFibNumber = firstFibNumber + secondFibNumber;
                firstFibNumber = newNumber;
            }

            Console.WriteLine("The sum of the even - valued terms fibonacci numbers " + sumOfAllEvenFib);
        }
    }
}
